from telegram.ext import ConversationHandler

# Defining conversation states as a range of integers
(
    # --- Customer Flows ---
    # Payment
    AWAITING_AMOUNT,
    AWAITING_RECEIPT,
    # Purchase
    SELECTING_CATEGORY,
    SELECTING_PLAN,
    CONFIRMING_PURCHASE,
    SELECTING_PAYMENT_METHOD,
    # Gift Card
    AWAITING_GIFT_CODE,
    # Service Management
    AWAITING_SERVICE_NOTE,
    AWAITING_RENEWAL_CONFIRMATION,
    AWAITING_CANCELLATION_CONFIRMATION,
    # Online Payment
    AWAITING_ONLINE_PAYMENT_VERIFICATION,

    # --- Admin Flows ---
    # Gift Card Creation
    AWAITING_GIFT_AMOUNT,
    AWAITING_GIFT_COUNT,
    # User Management
    AWAITING_USER_ID_FOR_SEARCH,
    AWAITING_AMOUNT_TO_ADD,
    # Broadcast
    AWAITING_BROADCAST_MESSAGE,
    CONFIRMING_BROADCAST,

    # --- Admin Settings Sub-flows ---
    ADMIN_SETTINGS_MENU,
    # Plan Management
    PLAN_MANAGEMENT_MENU,
    AWAITING_PLAN_NAME,
    AWAITING_PLAN_CATEGORY,
    AWAITING_PLAN_DURATION,
    AWAITING_PLAN_TRAFFIC,
    AWAITING_PLAN_PRICE,
    AWAITING_PLAN_DEVICE_LIMIT,
    CONFIRMING_PLAN_CREATION,
    # Panel Management
    SELECTING_PANEL_TO_MANAGE,
    MANAGING_SPECIFIC_PANEL,
    CONFIRMING_PANEL_DELETION,
    AWAITING_PANEL_NAME,
    AWAITING_PANEL_URL,
    AWAITING_PANEL_USERNAME,
    AWAITING_PANEL_PASSWORD,
    CONFIRMING_PANEL_CREATION,
    SELECTING_FIELD_TO_EDIT_PANEL,
    AWAITING_NEW_PANEL_VALUE,
    # Text Editing
    EDIT_TEXTS_NAVIGATE,
    AWAITING_NEW_TEXT_VALUE,
    # General & Payment Settings
    PAYMENT_SETTINGS_MENU,
    GENERAL_SETTINGS_MENU,
    AWAITING_NEW_SETTING_VALUE,
    # Commission Settings
    COMMISSION_SETTINGS_MENU,
    AWAITING_COMMISSION_THRESHOLD,
    AWAITING_COMMISSION_RATE,

) = range(47) # The range is updated to cover all states

# A constant to end the conversation from anywhere
END_CONVERSION = ConversationHandler.END